security:
  oauth2:
    client:
      client-id: oauth2_client
      client-secret: oauth2_client_secret
      scope: openid, read, write
      auto-approve-scopes: .*
      authorized-grant-types: authorization_code,refresh_token,password
    authorization:
      check-token-access: permitAll()
    resource.jwt:
      key-pair:
        alias: mytestkey
        store-password: mystorepass
server:
  port: 8081
  servlet:
    context-path: /authserver
logging:
  level:
    org.springframework.security: DEBUG